### ISSUE TITLE
Tipo de Combustible como atributo de Modelo

### ISSUE THREAD

**Issue by latacita** [lgo76/tallercan#1]
¿El tipo de combustible no sería más bien atributo de la clase Modelo? Cuando te preguntan el modelo de coche se dice un Scenic gasolina 110CV, por ejemplo. De hecho, en modelo yo metería también la potencia. Al leer el siguiente diagrama (el de las reparaciones) me parece todavía más lógico pasar al tipo de combustible al modelo. No te cobran lo mismo por los servicios, incluso para el mismo modelo de coche, si son diesel o gasolina.

**Comment by lgo76** [comment]
Sí, tienes razón. Elimino el atributo tipoCombustible de la clase Vehiculo y añado a la clase Modelo los atributos tipoCombustible y potencia, tanto en el proyecto mdzip como en las clases de dominio. Ya está actualizado en la rama develop.
